### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mlucool** [deshaw/jupyterlab-limit-output#3]
With limit output set head/tail set to 50 characters, the following reproducers a memory leak likely in this plugin:

```
import sys
import time

for _ in range(1_000):
    sys.stderr.write('w'*1000)
    sys.stderr.flush()
    time.sleep(0.01)
```

If you watch process memory it shoots up rapidly. When you clear all outputs it still stays high. Looking at a post-clear all outputs heap snapshot you can see the old strings there:
![image](https://user-images.githubusercontent.com/1813603/224370487-b2bd95b9-165b-4862-9dd2-cee0c1093d5d.png)

It's not clear the cause, but maybe we need to do something special for dispose?

**Comment by krassowski** [comment]
I see a memory leak associated with the use of context menu over the output node (which can be used to select "Clear Outputs" or "Clear All Outputs").

<details>

Here is the diff when using command palette:

![Screenshot from 2023-03-12 16-59-26](https://user-images.githubusercontent.com/5832902/224560173-288b2a52-9fe5-4b5c-a405-b372487ebc5e.png)

And here is one when using context menu on the output:

![Screenshot from 2023-03-12 17-01-34](https://user-images.githubusercontent.com/5832902/224560214-1ef24b0c-3c26-44b6-afb1-5628f3b20496.png)

</details>

This is because when context menu gets invoked, the event gets retained on `this._contextMenuEvent` in [`evtContextMenu`](https://github.com/jupyterlab/jupyterlab/blob/cbf39798a05dfbf533b5706b6e1dbd1cc65b00f5/packages/application/src/frontend.ts#L179-L180) to enable later access by [`contextMenuHitTest()`](https://github.com/jupyterlab/jupyterlab/blob/cbf39798a05dfbf533b5706b6e1dbd1cc65b00f5/packages/application/src/frontend.ts#L144-L146) if needed.

![Screenshot from 2023-03-12 17-07-12](https://user-images.githubusercontent.com/5832902/224560505-abe6a2b4-837b-44b0-8cb6-df6f52528235.png)

As for fixing this, we could empty the contents of the node on disposal. This way the detached node will still be there but it will not contain a reference to the long string or anything else, allowing those to be freed. Any solution that would dispose the problematic event reference would break `contextMenuHitTest` which is relied upon by extensions.

Can you confirm that you do not see a memory leak when using command palette to clear outputs?

**Comment by mlucool** [comment]
I can no longer reproduce this without limit output. I must have cleared output differently,
_____
Looking at this more, I think this is an upstream bug and maybe limit output makes it worse.

Given and no limit output plugin installed:
```
import sys
import time

for _ in range(10):
    sys.stderr.write('w'*10_000)
    sys.stderr.flush()
    time.sleep(0.01)
```
Then I run clear output from the command pallet, I would expect to see no `wwwww...` strings in the heap snapshot, but I do.

That being said, it seems the command palette does better than clear output for freeing memory when this plugin is enabled.
